# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3bbb6e193f57a56ea5195d0774e6f174edb68f52ce515639b1e5e66b3ed5b8c50c8f08253e2513ad29bc8ed4a625be86f572d15348aa43639a7153e87cb48cf

test:
  secret_key_base: d734619c78ab593aeeb019ae49f421ceda1dc989f2630e1619d3bee8fe874b32598c4121344b0544d2dbf5d53aaaf9dba98030e9cb8e6788d9c23e8fd7d6b83e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
